/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawalRouteImport } from './routes/withdrawal'
import { Route as UpgradeTierRouteImport } from './routes/upgrade-tier'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ApplyGrantRouteImport } from './routes/apply-grant'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminUserIdRouteImport } from './routes/admin_.$userId'

const WithdrawalRoute = WithdrawalRouteImport.update({
  id: '/withdrawal',
  path: '/withdrawal',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeTierRoute = UpgradeTierRouteImport.update({
  id: '/upgrade-tier',
  path: '/upgrade-tier',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyGrantRoute = ApplyGrantRouteImport.update({
  id: '/apply-grant',
  path: '/apply-grant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserIdRoute = AdminUserIdRouteImport.update({
  id: '/admin_/$userId',
  path: '/admin/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply-grant': typeof ApplyGrantRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upgrade-tier': typeof UpgradeTierRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin/$userId': typeof AdminUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply-grant': typeof ApplyGrantRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upgrade-tier': typeof UpgradeTierRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin/$userId': typeof AdminUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/apply-grant': typeof ApplyGrantRoute
  '/dashboard': typeof DashboardRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/upgrade-tier': typeof UpgradeTierRoute
  '/withdrawal': typeof WithdrawalRoute
  '/admin_/$userId': typeof AdminUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/apply-grant'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/upgrade-tier'
    | '/withdrawal'
    | '/admin/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-login'
    | '/apply-grant'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/upgrade-tier'
    | '/withdrawal'
    | '/admin/$userId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-login'
    | '/apply-grant'
    | '/dashboard'
    | '/signin'
    | '/signup'
    | '/upgrade-tier'
    | '/withdrawal'
    | '/admin_/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApplyGrantRoute: typeof ApplyGrantRoute
  DashboardRoute: typeof DashboardRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  UpgradeTierRoute: typeof UpgradeTierRoute
  WithdrawalRoute: typeof WithdrawalRoute
  AdminUserIdRoute: typeof AdminUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdrawal': {
      id: '/withdrawal'
      path: '/withdrawal'
      fullPath: '/withdrawal'
      preLoaderRoute: typeof WithdrawalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade-tier': {
      id: '/upgrade-tier'
      path: '/upgrade-tier'
      fullPath: '/upgrade-tier'
      preLoaderRoute: typeof UpgradeTierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply-grant': {
      id: '/apply-grant'
      path: '/apply-grant'
      fullPath: '/apply-grant'
      preLoaderRoute: typeof ApplyGrantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/$userId': {
      id: '/admin_/$userId'
      path: '/admin/$userId'
      fullPath: '/admin/$userId'
      preLoaderRoute: typeof AdminUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApplyGrantRoute: ApplyGrantRoute,
  DashboardRoute: DashboardRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  UpgradeTierRoute: UpgradeTierRoute,
  WithdrawalRoute: WithdrawalRoute,
  AdminUserIdRoute: AdminUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
