
ALTER TABLE public.profiles
  ADD COLUMN IF NOT EXISTS tier INT NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS tier_status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS requested_tier INT,
  ADD COLUMN IF NOT EXISTS id_front_url TEXT,
  ADD COLUMN IF NOT EXISTS id_back_url TEXT,
  ADD COLUMN IF NOT EXISTS ssn_card_url TEXT,
  ADD COLUMN IF NOT EXISTS selfie_url TEXT,
  ADD COLUMN IF NOT EXISTS ssn_last4 TEXT,
  ADD COLUMN IF NOT EXISTS verification_submitted_at TIMESTAMPTZ;
